application: bible-citation
version: 1
runtime: go
api_version: go1

handlers:
- url: /bower_components
  static_dir: bower_components

- url: /$
  static_files: index.html
  upload: index.html

- url: /(audio/.*\.(html|js|css))$
  static_files: \1
  upload: audio/.*\.(html|js|css)$

#- url: /.*
#  script: _go_app
